### ISSUE TITLE
Stringify causes problems with got package

### ISSUE THREAD

**Issue by sdomagala** [danielstjules/swaddle#4]
Line 254:
```
// Need to stringify for got/fetch
      opts.body = JSON.stringify(opts.body)
```

causes issues because `got` have validation like:
```
if ((opts.form || opts.json) && !isPlainObj(body)) {
	throw new TypeError('options.body must be a plain Object when options.form or options.json is used');
}
```
and string is not an object, so it throws.

Example usage:

```
documentService(tenant).data(topic).post, { body: payload, ...headers} );
```

I would add PR to remove this functionality, but since this code is there I guess there was a reason for it ;p 

And BTW. there is no example with both headers and body, maybe it's worth to update documentation with it

**Comment by danielstjules** [comment]
@sdomagala Are you running got 6.7.1? If not, it looks like there were major breaking changes with 7.0.

The check and logic is present in 7.0:
* https://github.com/sindresorhus/got/blob/01b5abdb730610e75e1fdea04cf834e2d8c17995/index.js#L319-L321

But not in 6.7.1:
* https://github.com/sindresorhus/got/blob/52da6067ddac5250d6c2e76af9a150b9cf4ba025/index.js#L241-L247

**Comment by danielstjules** [comment]
7.0 was released just 2 days ago 😅
I'd recommend using 6.7.1 until we can update support. I might patch it to support both old and new versions, or just slap on a min version requirement for the dep.

**Comment by danielstjules** [comment]
For reference, list of breaking changes are here: https://github.com/sindresorhus/got/releases/tag/v7.0.0

Commit in question: https://github.com/sindresorhus/got/commit/51a3eafbdfa2e98e36a6231cd16c80ca16b6523b

**Comment by sdomagala** [comment]
Thanks again for taking time for looking at this.
Maybe you could add to docs information on what major releases those packages were tested on? :)

**Comment by danielstjules** [comment]
I'll keep this open for now to track the change. And yea, will update to include integration tests with various versions of the packages, and includes notes in docs. :)

**Comment by danielstjules** [comment]
Latest release adds support for got 7 and drops support for got 6. Thanks again!
